"""Report renderer -- convert a FinalReport into a professional markdown deliverable."""
from __future__ import annotations

from typing import List

from .models import FinalReport, RoadmapItem
from .utils import format_percent, humanize_dollars


class ReportRenderer:
    """Render the final report as structured markdown."""

    def __init__(self, report: FinalReport):
        self.report = report

    def render(self) -> str:
        lines: List[str] = []
        lines.append("# FIRE Early Retirement Planner Report")
        lines.append("")
        lines.append("> **Disclaimer:** " + self.report.disclaimer
        )
        lines.append("")

        # Summary
        lines.append("## Summary")
        lines.append(f"- **Composite score:** {self.report.composite_score:.1f}/100")
        lines.append(f"- **Confidence level:** {self.report.confidence_level}")
        sim = self.report.simulation_result
        lines.append(
            f"- **Plan success probability:** {format_percent(sim.success_probability, 1)}"
        )
        lines.append(
            f"- **Ruin probability:** {format_percent(sim.ruin_probability, 1)}"
        )
        lines.append(
            f"- **Median final balance:** {humanize_dollars(sim.median_final_balance)}"
        )
        lines.append(
            f"- **Withdrawal rate used:** {format_percent(sim.withdrawal_rate_used, 2)}"
        )
        lines.append("")

        # Risk screen
        rs = self.report.risk_screen
        lines.append("## Risk & Suitability Gate")
        lines.append(f"- **Verdict:** {rs.verdict.value.upper()}")
        if rs.flags:
            lines.append("### Red flags")
            for flag in rs.flags:
                lines.append(f"- {flag}")
        if rs.warnings:
            lines.append("### Warnings")
            for warning in rs.warnings:
                lines.append(f"- {warning}")
        if rs.suggestions:
            lines.append("### Suggestions")
            for suggestion in rs.suggestions:
                lines.append(f"- {suggestion}")
        lines.append("")

        # Dimension scores
        lines.append("## Dimension Scores")
        lines.append("| Dimension | Score | Weight | Evidence/Assumption |")
        lines.append("|-----------|-------|--------|---------------------|")
        for d in self.report.dimension_scores:
            evidence = d.evidence
            if d.assumption:
                evidence += f" (assumption: {d.assumption})"
            lines.append(
                f"| {d.name} | {d.score:.0f}/100 | {d.weight:.0%} | {evidence} |"
            )
        lines.append("")
        for d in self.report.dimension_scores:
            lines.append(f"- **{d.name}:** {d.rationale}")
        lines.append("")

        # Allocation score
        alloc = self.report.allocation_score
        lines.append("## Allocation Score Detail")
        lines.append(f"- **Overall:** {alloc.overall_score:.0f}/100")
        lines.append(f"- **Diversification:** {alloc.diversification_score:.0f}/100")
        lines.append(f"- **Fee drag:** {alloc.fee_drag_score:.0f}/100")
        lines.append(f"- **Glide path:** {alloc.glide_path_score:.0f}/100")
        lines.append(f"- **Tax efficiency:** {alloc.tax_efficiency_score:.0f}/100")
        lines.append(f"- **Rationale:** {alloc.rationale}")
        lines.append("")

        # Findings
        lines.append("## Findings")
        for category in ["strengths", "gaps", "risks"]:
            lines.append(f"### {category.capitalize()}")
            for item in self.report.findings.get(category, []):
                lines.append(f"- {item}")
            if not self.report.findings.get(category):
                lines.append("- None identified.")
        lines.append("")

        # Roadmap
        lines.append("## Prioritized Roadmap (Impact -- Effort)")
        lines.append("| Priority | Action | Impact | Effort | I/E | Rationale | Evidence |")
        lines.append("|----------|--------|--------|--------|-----|-----------|----------|")
        for item in self.report.roadmap:
            lines.append(
                f"| {item.priority.value} | {item.title} | {item.impact} | {item.effort} | "
                f"{item.impact_x_effort():.2f} | {item.rationale} | {item.evidence} |"
            )
        lines.append("")

        # Sources & assumptions
        lines.append("## Sources")
        for name, source in self.report.sources:
            lines.append(f"- {name}: {source}")
        lines.append("")
        lines.append("## Assumptions")
        for assumption in self.report.assumptions:
            lines.append(f"- {assumption}")
        lines.append("")
        lines.append("---")
        lines.append(
            "*This report was generated by the fire-early-retirement-planner harness. "
            "All projections are probabilistic, not guarantees.*"
        )

        return "\n".join(lines)
